import json

# customized functions
from lib import sys_func

def initialConfig(config_path):
    config_dict = {
        "setup": False,
        "vs_id_path": "loginID.txt",
        "cr_id_path": "CRID.txt",
        "list_path": "List.txt",
        "phone_path": "Phonelist.txt",
        "google_secret_path": "secret.json",
        "google_token_path": "token.json",
        "google_cal_id": ['primary'],
        "url_path": "sys\web_config.json",
        "theme": "DefaultNoMoreNagging", 
        "digi_hr": 6,
        "digi_min": 0,
        "digi_repeat": 8,
        "am_clinic_hr": 8,
        "am_clinic_min": 0,
        "pm_clinic_hr": 12,
        "pm_clinic_min": 30,
        "am_sms_hr": 9,
        "am_sms_min": 0,
        "pm_sms_hr": 16,
        "pm_sms_min": 0
    }
    data = json.dumps(config_dict, ensure_ascii=False)
    sys_func.saveFile(config_path, data)
    return config_dict

def initialUrl(url_path):
    url_dict = {
        "portal_url": "http://portal.ntuh.gov.tw/General/Login.aspx",
        "digisign_replace_url": "http://ihisaw.ntuh.gov.tw/WebApplication/DigitalSignature/DSExecuteEmpReplace.aspx?SESSION=",
        "digisign_background_url": "http://ihisaw.ntuh.gov.tw/WebApplication/DigitalSignature/BackGroundDS.aspx?SESSION=",
        "open_clinic_url": "http://hisaw.ntuh.gov.tw/WebApplication/Clinics/OpenClinicsByClinicNo.aspx?SESSION=",
        "send_sms_url": "http://ihisaw.ntuh.gov.tw/WebApplication/OtherIndependentProj/CriticalVentilator/MessageSend.aspx?SESSION=",
        "exam_query_url": "http://hisaw.ntuh.gov.tw/WebApplication/Radiology/ReadOnlyExaPatientListQuery.aspx?SESSION=",
        "query_pt_url": "http://hisaw.ntuh.gov.tw/WebApplication/OutPatientAdministration/QueryModifyPatBase.aspx?SESSION=",
        "clinic_offduty_verify_url": "http://hisaw.ntuh.gov.tw/WebApplication/OPTManagement/VerifyOffDutiesAdm.aspx?SESSION=",
        "clinic_mod_staffverify_url": "http://hisaw.ntuh.gov.tw/WebApplication/OPTManagement/VerifyModificationStaff.aspx?SESSION=",
        "clinic_mod_verify_url": "http://hisaw.ntuh.gov.tw/WebApplication/OPTManagement/VerifyModificationAdm.aspx?SESSION=",
        "hosp_name": "總院區",
        "dept_name": "家庭醫學部",
        "hosp_list_ele": "ddlHospital",
        "quick_menu_ele": "rdblQuickMenu_0",
        "username_input_ele": "txtUserID",
        "password_input_ele": "txtPass",
        "captcha_img_ele": "imgVerifyCode",
        "captcha_input_ele": "txtVerifyCode",
        "submit_ele": "imgBtnSubmitNew",
        "digi_doc_id": "NTUHWeb1_txbEmpNO",
        "digi_update_panel": "NTUHWeb1_UpdatePanel1",
        "digi_refresh_btn": "NTUHWeb1_btnRefresh",
        "digi_count_text": "NTUHWeb1_lblUnDsCnts",
        "digi_new_id": "NTUHWeb1_txbEmpNoNew",
        "digi_tran_btn": "NTUHWeb1_btnUpdate",
        "digi_EMR_cbx": "NTUHWeb1_dgrEmrRecord_ctl01_cbxSelectAll",
        "digi_DRUG_cbx": "NTUHWeb1_dgrDrugGivenRecord_ctl01_cbxSelectAll",
        "digiback_pin": "NTUHWeb1_txbPinCode",
        "digiback_btn": "NTUHWeb1_btnBackGroundDSByPCSC",
        "digiback_ddl_reason": "reasonDDL-id > option:nth-child(1)",
        "digiback_ddl_confirm": "body > div > div.ui-dialog-buttonpane.ui-widget-content.ui-helper-clearfix > div > button:nth-child(1)",
        "clinic_hosp_list": "NTUHWeb1_HospDropList",
        "clinic_dept_list": "NTUHWeb1_DeptDropList",
        "clinic_year": "NTUHWeb1_DateTextBoxYearMonthDayInputUI1_YearInput",
        "clinic_month": "NTUHWeb1_DateTextBoxYearMonthDayInputUI1_MonthInput",
        "clinic_day": "NTUHWeb1_DateTextBoxYearMonthDayInputUI1_DayInput",
        "clinic_ampm_list": "NTUHWeb1_AMPMDropList",
        "clinic_num_input": "NTUHWeb1_ClinicNoInput",
        "clinic_query_btn": "NTUHWeb1_QueryScheduleList",
        "clinic_list_prefix": "NTUHWeb1_ClinicsListGrid_ctl",
        "clinic_btn_suffix": "_LinkButtonSelect",
        "clinic_num_suffix": "_ClinicNo",
        "clinic_dr_suffix": "_MainDrName",
        "clinic_start_btn": "NTUHWeb1_StartClinics",
        "clinic_nurse_btn": "NTUHWeb1_btnNurseSave",
        "clinic_back_btn": "NTUHWeb1_BackToTopPanel",
        "clinic_pt_detail_btn": "NTUHWeb1_ShowDetailPatInfo",
        "clinic_pt_detail": "NTUHWeb1_PatientDefailInfoLabel",
        "clinic_all_pt_btn": "NTUHWeb1_CheckBoxAllPatient",
        "clinic_pt_prefix": "NTUHWeb1_PatSimpleList_ctl",
        "clinic_pt_suffix": "_VisitSeqnoPlusName",
        "clinic_ptpage_other_func":"NTUHWeb1_ClinicsOtherFunction",
        "clinic_ptpage_change_cred":"NTUHWeb1_RepeaterPageLinkList_ctl13_LinkPageName",
        "clinic_cred_input":"NTUHWeb1_RewardEmpNoTextBoxInput",
        "clinic_cred_change_btn":"NTUHWeb1_ModifyRewardEmpNoButton",
        "clinic_cred_return_pt":"NTUHWeb1_ButtonReturnConfirmDiagnosisOrder",
        "clinic_ptpage_return":"NTUHWeb1_Return",
        "sms_phone_ele": "NTUHWeb1_PHSTelNo",
        "sms_type_btn": "NTUHWeb1_rdbNormal",
        "sms_msg_input": "NTUHWeb1_MessageContent",
        "sms_send_btn": "NTUHWeb1_btnSendSMSAndEmail",
        "exam_ampm_list": "NTUHWeb1_ddlShiftType",
        "exam_unit_list": "NTUHWeb1_ddlExaUnitList",
        "exam_origin_list": "NTUHWeb1_ddlPatClass",
        "exam_item_list": "NTUHWeb1_ddlExaItemList",
        "exam_query_date": "NTUHWeb1_txbQueryStartDate",
        "exam_query_btn": "NTUHWeb1_btnQueryBySchedule",
        "exam_query_table": "NTUHWeb1_grvPatientOrderList",
        "query_chart_ele": "NTUHWeb1_txtChartNo",
        "query_btn": "NTUHWeb1_btnQuery",
        "query_home_btn": "NTUHWeb1_btnHome2",
        "query_pt_cht_sur": "NTUHWeb1_txtPatBaseFChtName",
        "query_pt_cht_given": "NTUHWeb1_txtPatBaseGChtName",
        "query_pt_areacode": "NTUHWeb1_txtPatBaseContTelAreaCode",
        "query_pt_tel": "NTUHWeb1_txtPatBaseContTelNo",
        "query_pt_mobile": "NTUHWeb1_txtPatBaseMobile",
        "verify_offduty_list": "NTUHWebVerifyOffDutiesAdm_dtgQueryList",
        "verify_offduty_btn": "NTUHWebVerifyOffDutiesAdm_btnApply",
        "verify_offduty_back": "NTUHWebVerifyOffDutiesAdm_btnBack",
        "verify_modify_list": "NTUHWebVerifyModificationAdm_dtgQueryList",
        "verify_modify_btn": "NTUHWebVerifyModificationAdm_btnApply",
        "verify_modify_back": "NTUHWebVerifyModificationAdm_btnBack",
        "verify_staff_list": "NTUHWebVerifyModificationStaff_dtgQueryList",
        "verify_staff_btn": "NTUHWebVerifyModificationStaff_btnApply",
        "verify_staff_back": "NTUHWebVerifyModificationStaff_btnBack",    
    }
    data = json.dumps(url_dict, ensure_ascii=False)
    sys_func.saveFile(url_path, data)
    return url_dict
