def initialConfig():
    config_dict = {
        "setup": False,
        "log_path": "sys\log.txt",
        "error_log_path": "sys\error_log.txt",
        "url_path": "sys\web_config.json",
        "chrome_driver_path": "sys\chromedriver.exe",
        "ie_driver_path": "sys\IEDriverServer32.exe",
        "edge_driver_path": "sys\msedgedriver.exe",
        "vs_id_path": "VSID.txt",
        "cr_id_path": "CRID.txt",
        "list_path": "List.txt",
        "phone_path": "Phonelist.txt",
        "sms_path": "SMStext.txt",
        "vslist_path": "VSList.txt",
        "google_secret_path": "secret.json",
        "google_token_path": "token.json",
        "google_cal_id": ['primary'],
        "HCA_service_name": "HCAServiSign.exe",
        "pin_window_title": "CS 5.0",
        "theme": "DefaultNoMoreNagging",
        "digi_switch": False,
        "digi_hr": 6,
        "digi_min": 0,
        "digi_repeat": 8,
        "clinic_switch": False,
        "am_clinic_hr": 8,
        "am_clinic_min": 0,
        "pm_clinic_hr": 12,
        "pm_clinic_min": 30,
        "sms_switch": False,
        "am_sms_hr": 9,
        "am_sms_min": 0,
        "pm_sms_hr": 16,
        "pm_sms_min": 0,
        "resume_switch": True,
        "hide_web": False,
        "testenv": False,
    }
    return config_dict

def initialUrl():
    url_dict = {
        "portal_url": "http://portal.ntuh.gov.tw/General/Login.aspx",
        "digisign_replace_url": "http://ihisaw.ntuh.gov.tw/WebApplication/DigitalSignature/DSExecuteEmpReplace.aspx?SESSION=",
        "digisign_background_url": "http://ihisaw.ntuh.gov.tw/WebApplication/DigitalSignature/BackGroundDS.aspx?SESSION=",
        "digisign_query_url": "http://ihisaw.ntuh.gov.tw/WebApplication/DigitalSignature/DsQuery.aspx?SESSION=",
        "open_clinic_url": "http://hisaw.ntuh.gov.tw/WebApplication/Clinics/OpenClinicsByClinicNo.aspx?SESSION=",
        "send_sms_url": "http://ihisaw.ntuh.gov.tw/WebApplication/OtherIndependentProj/CriticalVentilator/MessageSend.aspx?SESSION=",
        "exam_query_url": "http://hisaw.ntuh.gov.tw/WebApplication/Radiology/ReadOnlyExaPatientListQuery.aspx?SESSION=",
        "query_pt_url": "http://hisaw.ntuh.gov.tw/WebApplication/OutPatientAdministration/QueryModifyPatBase.aspx?SESSION=",
        "clinic_offduty_verify_url": "http://hisaw.ntuh.gov.tw/WebApplication/OPTManagement/VerifyOffDutiesAdm.aspx?SESSION=",
        "clinic_mod_staffverify_url": "http://hisaw.ntuh.gov.tw/WebApplication/OPTManagement/VerifyModificationStaff.aspx?SESSION=",
        "clinic_mod_verify_url": "http://hisaw.ntuh.gov.tw/WebApplication/OPTManagement/VerifyModificationAdm.aspx?SESSION=",
        "hosp_name": "總院區",
        "dept_name": "家庭醫學部",
        "hosp_list_ele": "ddlHospital",
        "quick_menu_ele": "rdblQuickMenu_0",
        "username_input_ele": "txtUserID",
        "password_input_ele": "txtPass",
        "captcha_img_ele": "imgVerifyCode",
        "captcha_input_ele": "txtVerifyCode",
        "submit_ele": "imgBtnSubmitNew",
        "digi_doc_id": "NTUHWeb1_txbEmpNO",
        "digi_refresh_btn": "NTUHWeb1_btnRefresh",
        "digi_count_text": "NTUHWeb1_lblUnDsCnts",
        "digi_new_id": "NTUHWeb1_txbEmpNoNew",
        "digi_new_name": "NTUHWeb1_lblEmpNameNew",
        "digi_tran_btn": "NTUHWeb1_btnUpdate",
        "digi_EMR_cbx": "NTUHWeb1_dgrEmrRecord_ctl01_cbxSelectAll",
        "digi_DRUG_cbx": "NTUHWeb1_dgrDrugGivenRecord_ctl01_cbxSelectAll",
        "digiback_pin": "NTUHWeb1_txbPinCode",
        "digiback_btn": "NTUHWeb1_btnBackGroundDSByPCSC",
        "digiback_ddl_reason": "reasonDDL-id > option:nth-child(1)",
        "digiback_ddl_confirm": "body > div > div.ui-dialog-buttonpane.ui-widget-content.ui-helper-clearfix > div > button:nth-child(1)",
        "digiquery_pin": "NTUHWeb1_txbPinCode",
        "digiquery_ie_btn": "NTUHWeb1_btnDoSignatureByPCSC",
        "digiquery_chrome_btn": "NTUHWeb1_btnDoSignatureByCrossBroswer",
        "digiquery_refresh_btn": "NTUHWeb1_btnRefresh",
        "digiquery_count_text": "NTUHWeb1_lblUnDsCnts",
        "clinic_hosp_list": "NTUHWeb1_HospDropList",
        "clinic_dept_list": "NTUHWeb1_DeptDropList",
        "clinic_year": "NTUHWeb1_DateTextBoxYearMonthDayInputUI1_YearInput",
        "clinic_month": "NTUHWeb1_DateTextBoxYearMonthDayInputUI1_MonthInput",
        "clinic_day": "NTUHWeb1_DateTextBoxYearMonthDayInputUI1_DayInput",
        "clinic_ampm_list": "NTUHWeb1_AMPMDropList",
        "clinic_num_input": "NTUHWeb1_ClinicNoInput",
        "clinic_query_btn": "NTUHWeb1_QueryScheduleList",
        "clinic_list_prefix": "NTUHWeb1_ClinicsListGrid_ctl",
        "clinic_btn_suffix": "_LinkButtonSelect",
        "clinic_num_suffix": "_ClinicNo",
        "clinic_dr_suffix": "_MainDrName",
        "clinic_start_btn": "NTUHWeb1_StartClinics",
        "clinic_nurse_btn": "NTUHWeb1_btnNurseSave",
        "clinic_back_btn": "NTUHWeb1_BackToTopPanel",
        "clinic_pt_detail_btn": "NTUHWeb1_ShowDetailPatInfo",
        "clinic_pt_detail": "NTUHWeb1_PatientDefailInfoLabel",
        "clinic_all_pt_btn": "NTUHWeb1_CheckBoxAllPatient",
        "clinic_pt_prefix": "NTUHWeb1_PatSimpleList_ctl",
        "clinic_pt_suffix": "_VisitSeqnoPlusName",
        "clinic_ptpage_other_func":"NTUHWeb1_ClinicsOtherFunction",
        "clinic_ptpage_change_cred":"NTUHWeb1_RepeaterPageLinkList_ctl13_LinkPageName",
        "clinic_cred_input":"NTUHWeb1_RewardEmpNoTextBoxInput",
        "clinic_cred_change_btn":"NTUHWeb1_ModifyRewardEmpNoButton",
        "clinic_cred_return_pt":"NTUHWeb1_ButtonReturnConfirmDiagnosisOrder",
        "clinic_ptpage_return":"NTUHWeb1_Return",
        "clinic_med_author": "MedicalManagementAuthor.aspx",
        "clinic_med_author_reason": "RBList",
        "clinic_med_author_btn": "ConfirmButton",
        "sms_phone_ele": "NTUHWeb1_PHSTelNo",
        "sms_id_ele": "NTUHWeb1_tbxEMPNo",
        "sms_type_btn": "NTUHWeb1_rdbNormal",
        "sms_msg_input": "NTUHWeb1_MessageContent",
        "sms_send_btn": "NTUHWeb1_btnSendSMSAndEmail",
        "exam_ampm_list": "NTUHWeb1_ddlShiftType",
        "exam_unit_list": "NTUHWeb1_ddlExaUnitList",
        "exam_origin_list": "NTUHWeb1_ddlPatClass",
        "exam_item_list": "NTUHWeb1_ddlExaItemList",
        "exam_query_date": "NTUHWeb1_txbQueryStartDate",
        "exam_query_btn": "NTUHWeb1_btnQueryBySchedule",
        "exam_query_table": "NTUHWeb1_grvPatientOrderList",
        "query_chart_ele": "NTUHWeb1_txtChartNo",
        "query_btn": "NTUHWeb1_btnQuery",
        "query_home_btn": "NTUHWeb1_btnHome2",
        "query_pt_cht_sur": "NTUHWeb1_txtPatBaseFChtName",
        "query_pt_cht_given": "NTUHWeb1_txtPatBaseGChtName",
        "query_pt_areacode": "NTUHWeb1_txtPatBaseContTelAreaCode",
        "query_pt_tel": "NTUHWeb1_txtPatBaseContTelNo",
        "query_pt_mobile": "NTUHWeb1_txtPatBaseMobile",
        "verify_offduty_list": "NTUHWebVerifyOffDutiesAdm_dtgQueryList",
        "verify_offduty_btn": "NTUHWebVerifyOffDutiesAdm_btnApply",
        "verify_offduty_back": "NTUHWebVerifyOffDutiesAdm_btnBack",
        "verify_modify_list": "NTUHWebVerifyModificationAdm_dtgQueryList",
        "verify_modify_btn": "NTUHWebVerifyModificationAdm_btnApply",
        "verify_modify_back": "NTUHWebVerifyModificationAdm_btnBack",
        "verify_staff_list": "NTUHWebVerifyModificationStaff_dtgQueryList",
        "verify_staff_btn": "NTUHWebVerifyModificationStaff_btnApply",
        "verify_staff_back": "NTUHWebVerifyModificationStaff_btnBack",
        "hca_card_obj": "HCACard",
        "hca_card_api_obj": "HCACardAPI",
    }
    return url_dict

def initialSMS():
    sms_dict = {
        "amtext_prefix": "各位同仁早！今日",
        "pmtext_prefix": "各位同仁辛苦了，請記得電子簽章",
        "fripmtext_prefix": "各位同仁辛苦了，周末值班同仁請記得電子簽章",
        "noevent": "無其他行程",
        "allday": "全天",
        "Mon": "（一）",
        "Tue": "（二）",
        "Wed": "（三）",
        "Thu": "（四）",
        "Fri": "（五）",
        "Sat": "（六）",
        "Sun": "（日）",
        "digi_reminder": "各位同仁辛苦了，請記得電子簽章",
        "left_digi_prefix": "辛苦了，VS還有",
        "left_digi_suffix": "筆未簽章，請注意！",
        "left_digi_warning": "(此為提醒portal尚有未簽章)",
        "comma": "，",
        "end": "。",
    }
    return sms_dict